Table bancos{
    id int [pk, increment] //primary key 
    descripcion varchar
    created_at timestamp
    updated_at timestamp
}

Table monedas {
    id int [pk, increment]
    codigo varchar(10)
    descripcion varchar(100)
    simbolo varchar(10)
    estado boolean
    created_at timestamp
    updated_at timestamp
}

Table cuenta_bancarias {
    id int [pk, increment]
    banco_id int [not null, ref: > bancos.id]
    moneda_id int [not null, ref: > monedas.id]
    descripcion varchar(100)
    numero varchar(50)
    cci varchar(50)
    saldo_inicial decimal(15,2) [default: 0]
    mostrar_comprobante enum('Si', 'No') [default: 'No']
    created_at timestamp
    updated_at timestamp
}

Table tarjetas {
    id int [pk, increment]
    codigo varchar(10)
    descripcion varchar(100)
    created_at timestamp
    updated_at timestamp
}

Table plataformas {
    id int [pk, increment]
    nombre varchar(100)
    estado varchar(2)
    created_at timestamp
    updated_at timestamp
}

Table metodo_pagos {
    id int [pk, increment]
    codigo varchar(10)
    descripcion varchar(150)
    condicion_pago varchar(20)
    created_at timestamp
    updated_at timestamp
}

Table metodo_gastos {
    id int [pk, increment]
    descripcion varchar(150)
    created_at timestamp
    updated_at timestamp
}

Table atributos {
    id int [pk, increment]
    codigo varchar(100)
    descripcion varchar(50)
    estado boolean
    created_at timestamp
    updated_at timestamp
}

Table detraccions{
    id int [pk, increment]
    tipo_operacion varchar(10)
    codigo varchar(10)
    descripcion varchar(150)
    porcentaje decimal(5,2)
    activo boolean [default: true]
    created_at timestamp
    updated_at timestamp
}

Table unidades {
    id int [pk, increment]
    codigo varchar(10)
    descripcion varchar(100)
    simbolo varchar(10)
    estado enum('Si', 'No') [default: 'Si']
    created_at timestamp
    updated_at timestamp
}

Table traslados {
    id int [pk, increment]
    codigo varchar(20)
    descripcion varchar(100)
    descuenta_stock enum('SI', 'NO') [default: 'NO']
    created_at timestamp
    updated_at timestamp
}

Table login_imagens{
    id int [pk, increment]
    imagen varchar(255)
    estado boolean [default: true]
    created_at timestamp
    updated_at timestamp
}

Table logins {
    id int [pk, increment]
    compania_id int [not null, ref: > companias.id]
    posicion_formulario enum('IZQUIERDA', 'DERECHA') [default: 'DERECHA']
    mostrar_logo boolean [default: true]
    posicion_logo enum('SUPERIOR_IZQUIERDA', 'SUPERIOR_CENTRO', 'SUPERIOR_DERECHA') [default: 'SUPERIOR_IZQUIERDA']
    mostrar_facebook boolean [default: false]
    facebook varchar(255)
    mostrar_twitter boolean [default: false]
    twitter varchar(255)
    mostrar_instagram boolean [default: false]
    instagram varchar(255)
    mostrar_linkedin boolean [default: false]
    linkedin varchar(255)
    created_at timestamp
    updated_at timestamp
}

Table companias{
    id int [pk, increment]
    // Datos de la empresa
    ruc varchar(11)
    nombre varchar(255)
    nombre_comercial varchar(255)
    // Personalización
    logo varchar(255)
    cuenta_detraccion varchar(255)
    rubrica varchar(255)
    titulo_web varchar(255)
    logo_app varchar(255)
    // Entorno del sistema
    soap_tipo enum('demo','produccion')
    soap_envio enum('sunat','ose','osesendfact')
    soap_usuario varchar(255)
    soap_password varchar(255)

    // Consulta integrada de CPE
    cpe_client_id varchar(255)
    cpe_client_secret varchar(255)

    // SIRE
    sire_client_id varchar(255)
    sire_client_secret varchar(255)
    sire_usuario varchar(255)
    sire_password varchar(255)

    // QR API
    qr_api boolean [default: false]

    // Certificado QZ Tray
    digital_certificate_qztray varchar(255)
    private_certificate_qztray varchar(255)

    // Servicio PSE
    pse_habilitado boolean [default: false]
    pse_proveedor_id int
    pse_usuario varchar(255)
    pse_password varchar(255)

    // Configuración de pagos
    yape_habilitado boolean [default: false]
    mercado_pago_habilitado boolean [default: false]
    created_at timestamp
    updated_at timestamp
}

Table estilos {
    id int [pk, increment]
    nombre varchar(50)
    color varchar(20)
    modo varchar(20)
    menu_lateral varchar(20)
    estado varchar(10) [default: 'INACTIVO']
    created_at timestamp
    updated_at timestamp
}

Table motivos_gastos {
    id int [pk, increment]
    descripcion varchar(150)
    estado varchar(10) [default: 'INACTIVO']
    created_at timestamp
    updated_at timestamp
}

Table motivos_ingresos {
    id int [pk, increment]
    descripcion varchar(150)
    estado varchar(10) [default: 'INACTIVO']
    created_at timestamp
    updated_at timestamp
}

Table comprobante_ingresos {
    id int [pk, increment]
    descripcion varchar(150)
    estado enum('ACTIVO', 'INACTIVO') [default: 'INACTIVO']
    created_at timestamp
    updated_at timestamp
}

Table comprobante_gastos {
    id int [pk, increment]
    descripcion varchar(150)
    estado enum('ACTIVO', 'INACTIVO') [default: 'INACTIVO']
    created_at timestamp
    updated_at timestamp
}

Table sucursales {
    id int [pk, increment]
    descripcion varchar(150)
    pais varchar(100)
    departamento varchar(100)
    provincia varchar(100)
    distrito varchar(100)
    direccion_fiscal varchar(255)
    telefono varchar(30)
    direccion_comercial varchar(255)
    correo_contacto varchar(150)
    direccion_web varchar(255)
    informacion_adicional text
    codigo_sucursal varchar(20)
    estado enum
    cliente_id int [not null, ref: > clientes.id]
    created_at timestamp
    updated_at timestamp
}

Table Roles {
    id int [pk, increment]
    nombre varchar(100)
    descripcion varchar(255)
    estado boolean
    created_at timestamp
    updated_at timestamp
}

Table tipo_clientes {
    id int [pk, increment]
    nombre varchar(100)
    estado boolean
    created_at timestamp
    updated_at timestamp
}

Table clientes {
    id int [pk, increment]
    tipo_documento varchar(20)
    numero_documento varchar(30)
    nombre varchar(100)
    apellidos varchar(150)
    nombre_comercial varchar(150)
    codigo_interno varchar(50)
    nacionalidad varchar(100)
    tipo_cliente_id int [not null, ref: > tipo_clientes.id]
    codigo_barra varchar(100)
    direccion varchar(255)
    pais varchar(100)
    codigo_sucursal varchar(50)
    telefono varchar(30)
    correo_electronico varchar(150)
    sitio_web varchar(255)
    dias_credito int [default: 0]
    observaciones text
    estado boolean [default: true]
    created_at timestamp
    updated_at timestamp
}



